Fynn edits
EOP-Labs/M2TWEOP-library pull request #17
Opened 2022-11-11 22:51 UTC by thrillos

fixed doc comment that caused crash

Lua edu functions and fields:
Get edu entry by id (value below 500 is normal edu; > 500 is eop edu)
Get edu entry by edu type name
Get edu index by edu type name
set and get number of armour upgrade levels and the levels
set and get number of armour upgrade models and the models
Set primary/secondary stats for entry (armour, defense skill, shield, attack, charge)
Set any primary/secondary attack attribute
Added fields: Morale, MoraleLocked, Statfood1, Statfood2, Ammunition

Lua settlement struct fields:
All public order types
All income types
All pop growth types

Factionstruct: added kings purse

Lua console: Can use up/down arrow to go to previous commands

2022-11-12 18:39 UTC, EddieEldridge commented
I left some comments but overall this is brilliant! 

One small thing,  an you please add what you have put in the description into releaseDescription.md? 

The release notes for the release get pulled from whatever is in that file. 

Thanks!

2022-11-15 07:26 UTC, youneuoy commented on M2TWEOP Code/M2TWEOP library/eduThings.cpp
>  		entry->localizedDescrShort = shDescrMem;
looks like we have problem here) Check pls, i busy now. Wrong field i think(see field of entry and name of function).

2022-11-15 07:28 UTC, youneuoy commented on M2TWEOP-luaPlugin/luaPlugin/eopEduHelpers.cpp
> +    if (amount > 0)
condition can be reverted 
```
if(amount <=0)
{
return;
}
here we do work
```

2022-11-15 07:29 UTC, youneuoy commented on M2TWEOP-luaPlugin/luaPlugin/eopEduHelpers.cpp
> +        if (amount > curramount)
as above

2022-11-15 07:30 UTC, youneuoy commented on M2TWEOP-luaPlugin/luaPlugin/eopEduHelpers.cpp
> +            int8_t last_upgrade = *(int8_t*)((eduEn->ArmorUpgradeLevels) + (curramount-1));
here we have array, i.e. better use eduEn->ArmorUpgradeLevels[curramount-1], etc

2022-11-15 07:31 UTC, youneuoy commented on M2TWEOP-luaPlugin/luaPlugin/eopEduHelpers.cpp
> +                *(int8_t*)((eduEn->ArmorUpgradeLevels) + curramount + i) = last_upgrade;
as above

2022-11-15 07:31 UTC, youneuoy commented on M2TWEOP-luaPlugin/luaPlugin/eopEduHelpers.cpp
> +        return *(int8_t*)((eduEn->ArmorUpgradeLevels) + levelidx);
as above

2022-11-15 07:31 UTC, youneuoy commented on M2TWEOP-luaPlugin/luaPlugin/eopEduHelpers.cpp
> +        *(int8_t*)((eduEn->ArmorUpgradeLevels) + levelidx) = newlevel;
as above

2022-11-15 07:32 UTC, youneuoy commented on M2TWEOP-luaPlugin/luaPlugin/eopEduHelpers.cpp
> +    if (amount > 0 && amount < 5)
condition can be reverted

2022-11-15 07:32 UTC, youneuoy commented on M2TWEOP-luaPlugin/luaPlugin/eopEduHelpers.cpp
> +        if (amount > (curramount*2))
condition can be reverted

2022-11-15 07:33 UTC, youneuoy commented on M2TWEOP-luaPlugin/luaPlugin/eopEduHelpers.cpp
> +    }
better add return ""; to end of function

2022-11-15 07:34 UTC, youneuoy commented on M2TWEOP-luaPlugin/luaPlugin/eopEduHelpers.cpp
> +void eopEduHelpers::setArmourUpgradeModel(int idx, int levelidx, std::string newModel)
pass string parameters as const references(const string& newModel)

2022-11-15 07:36 UTC, youneuoy commented on M2TWEOP-luaPlugin/luaPlugin/eopEduHelpers.h
> +        spear = 1<<2,
add to enum 0 value( nothing=0)

2022-11-15 07:36 UTC, youneuoy commented on M2TWEOP-luaPlugin/luaPlugin/eopEduHelpers.h
> +        armour = 1<<1,
add to enum 0 value( nothing=0)

2022-11-15 07:36 UTC, youneuoy commented on M2TWEOP-luaPlugin/luaPlugin/luaEopEdu.cpp
> +		"attackAttr",
add to enum 0 value( nothing=0)

2022-11-15 07:36 UTC, youneuoy commented on M2TWEOP-luaPlugin/luaPlugin/luaEopEdu.cpp
> +		"eduStat",
add to enum 0 value( nothing=0)

2022-11-15 07:38 UTC, youneuoy commented on M2TWEOP-luaPlugin/luaPlugin/luaP.cpp
> +	types.factionStruct.set("KingsPurse", &factionStruct::KingsPurse);
add to comment above(documentation generated from it)

2022-11-15 07:38 UTC, youneuoy commented on M2TWEOP-luaPlugin/luaPlugin/luaP.cpp
> +	types.settlementStruct.set("PopGrowthBaseFarm", &settlementStruct::PopGrowthBaseFarm);
add allto comment above(documentation generated from it)

2022-11-15 07:39 UTC, youneuoy commented
@FynnTW :partying_face: . Look at my comments pls and do someting.

2022-11-15 07:43 UTC, youneuoy commented
@FynnTW always describe your updates here https://github.com/youneuoy/M2TWEOP-library/blob/Fynn-edits/documentationGenerator/releaseInfo/releaseDescription.md

2022-11-15 13:58 UTC, EddieEldridge requested changes

2022-11-15 13:58 UTC, Medik-GH commented on M2TWEOP-luaPlugin/luaPlugin/eopEduHelpers.cpp
> +	using namespace UnitEnums;
I think it might be better to put this at the top of the file once, that way it's easier to maintain and keep track of.

2022-11-15 13:58 UTC, Medik-GH commented on M2TWEOP-luaPlugin/luaPlugin/luaP.cpp
> +	types.EduEntry.set("StatFood1", &EduEntry::StatFood1);
Stat food???

2022-11-15 13:58 UTC, Medik-GH commented on M2TWEOP-luaPlugin/luaPlugin/luaP.cpp
> +	types.settlementStruct.set("PublicOrderSqualor", &settlementStruct::PublicOrderSqualor);
Can we set public order maluses corr ctly now?

2022-11-15 13:58 UTC, Medik-GH commented on M2TWEOP-luaPlugin/luaPlugin/luaP.h
> +	static std::vector<std::string> logCommands;
Are we using this?

2022-11-16 06:05 UTC, FynnTW commented on M2TWEOP-luaPlugin/luaPlugin/luaP.cpp
> +	types.EduEntry.set("StatFood1", &EduEntry::StatFood1);
edu stat not used by game can be used by modders to put in any other stat they want like unit loyalty or supply demand

2023-02-12 07:04 UTC, youneuoy commented on M2TWEOP-luaPlugin/luaPlugin/eopEduHelpers.cpp
> +	using namespace UnitEnums;
this is not problem i think, just very little detail)

2023-02-21 00:32 UTC, merged